'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    sales: 'Sales',
    salesHistory: 'Sales History',
    searchBySaleIdCustomer: 'Search by Sale ID or Customer',
    allSales: 'All Sales',
    inSelectedPeriod: 'In selected period',
    beforeDiscounts: 'Before discounts',
    afterExpenses: 'After expenses',
    recentSales: 'Recent Sales',
    loadingSales: 'Loading sales...',
    noSalesFound: 'No sales found',
    errorFetchingSales: 'Error fetching sales',
    remaining: 'Remaining',
    returns: 'Returns',
    reports: 'Reports',
    inventoryManagement: 'Inventory Management',
    loansCredit: 'Loans/Credit',
    loanHistory: 'Loan History',
    loanCreditManagement: 'Loan & Credit Management',
    loanHistorySubtitle: 'View and manage sales and payment history',
    fullyPaid: 'Fully Paid',
    partiallyPaid: 'Partially Paid',
    totalPaid: 'Total Paid',
    totalPending: 'Total Pending',
    salesAndPaymentHistory: 'Sales & Payment History',
    itemsSold: 'Items Sold',
    noPaymentHistory: 'No payment history',
    totalSalesAmount: 'Total Sales Amount',
    amountCollected: 'Amount Collected',
    yetToCollect: 'Yet to Collect',
    fromAllSales: 'from all sales',
    loadingData: 'Loading data...',
    totalProfit: 'Total Profit',
    
    // Dashboard
    welcomeBack: 'Welcome back! Here\'s your business overview',
    todaysSales: 'Today\'s Sales',
    totalRevenue: 'Total Revenue',
    totalProducts: 'Total Products',
    lowStockItems: 'Low Stock Items',
    pendingReturns: 'Pending Returns',
    recentActivities: 'Recent Activities',
    viewAll: 'View All',
    fromYesterday: 'from yesterday',
    thisMonth: 'this month',
    requiresAttention: 'Requires attention',
    processSoon: 'Process soon',
    
    // Product Management
    productManagement: 'Product Management',
    addProduct: 'Add Product',
    addCategory: 'Add Category',
    categories: 'Categories',
    searchProducts: 'Search products...',
    allCategories: 'All Categories',
    price: 'Price',
    stock: 'Stock',
    minStock: 'Min Stock',
    category: 'Category',
    description: 'Description',
    barcode: 'Barcode',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product',
    productName: 'Product Name',
    quantity: 'Quantity',
    minimumStock: 'Minimum Stock',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    deleteProduct: 'Delete Product',
    deleteProductConfirm: 'Are you sure you want to delete this product?',
    deleteCategory: 'Delete Category',
    deleteCategoryConfirm: 'Are you sure you want to delete this category? Products in this category will not be deleted.',
    editCategory: 'Edit Category',
    addNewCategory: 'Add New Category',
    categoryName: 'Category Name',
    categoryDescription: 'Description',
    selectCategory: 'Select Category',
    loadingProducts: 'Loading products...',
    noProductsFound: 'No products found',
    noCategoriesFound: 'No categories found',
    boxes: 'boxes',
    units: 'units',
    products: 'Products',
    unitsPerBox: 'Units Per Box',
    profitPerUnit: 'Profit per Unit (PKR)',
    profitPerBox: 'Profit per Box (PKR)',
    profitEarnedPerUnit: 'Profit earned per unit',
    profitEarnedPerBox: 'Profit earned per box',
    addStockBy: 'Add Stock By:',
    individualQuantity: 'Individual Quantity',
    boxesUnits: 'Boxes + Units',
    totalQuantityUnits: 'Total Quantity (in units)',
    enterTotalUnits: 'Enter total number of units',
    thisEquals: 'This equals:',
    and: 'and',
    looseUnits: 'loose units',
    numberOfBoxes: 'Number of Boxes',
    howManyBoxes: 'How many boxes?',
    extraUnits: 'Extra units',
    minimumStockAlert: 'Minimum Stock Alert (in units)',
    alertWhenStockFalls: 'Alert when stock falls below',
    updateProduct: 'Update Product',
    failedToUpdateProduct: 'Failed to update product',
    failedToCreateProduct: 'Failed to create product',
    failedToDeleteProduct: 'Failed to delete product',
    productDeletedSuccessfully: 'Product deleted successfully',
    cannotDeleteProductWithHistory: 'Cannot delete this product. It has sales or return history. Set quantity to 0 instead.',
    failedToUpdateCategory: 'Failed to update category',
    failedToCreateCategory: 'Failed to create category',
    failedToDeleteCategory: 'Failed to delete category',
    saving: 'Saving...',
    updateCategory: 'Update Category',
    enterCategoryName: 'Enter category name',
    enterCategoryDescription: 'Enter category description (optional)',
    howManyUnitsInBox: 'How many units in one box?',
    alertWhenStockFallsBelow: 'Alert when stock falls below this',
    descriptionOptional: 'Description (Optional)',
    
    // Sales POS
    searchProducts: 'Search Products',
    searchProductsBarcode: 'Search by name or scan barcode...',
    shoppingCart: 'Shopping Cart',
    items: 'items',
    emptyCart: 'Your cart is empty',
    addItemsToStart: 'Add items to get started',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    checkout: 'Checkout',
    customerInfo: 'Customer Information',
    customerName: 'Customer Name',
    phone: 'Phone',
    email: 'Email',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    upi: 'UPI',
    processSale: 'Process Sale',
    receipt: 'Receipt',
    paymentSuccessful: 'Payment Successful!',
    saleId: 'Sale ID',
    date: 'Date',
    printReceipt: 'Print Receipt',
    remove: 'Remove',
    grandTotal: 'Grand Total',
    proceedToCheckout: 'Proceed to Checkout',
    enterCustomerName: 'Enter customer name',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter phone number',
    emailOptional: 'Email (Optional)',
    enterEmailAddress: 'Enter email address',
    paymentType: 'Payment Type',
    fullPayment: 'Full Payment',
    partialPayment: 'Partial Payment (Loan/Credit)',
    amountPaidNow: 'Amount Paid Now',
    enterAmountPayingNow: 'Enter amount customer is paying now',
    remaining: 'Remaining',
    dueDate: 'Due Date (Optional)',
    totalAmount: 'Total Amount',
    amountPayingNow: 'Amount Paying Now',
    remainingAmount: 'Remaining Amount',
    notEnoughStock: 'Not enough stock available!',
    outOfStockProduct: 'This product is out of stock!',
    cartEmpty: 'Cart is empty! Please add items to cart.',
    saleProcessedSuccess: 'Sale processed successfully!',
    failedToProcessSale: 'Failed to process sale. Please try again.',
    errorProcessingSale: 'Error processing sale. Please try again.',
    newSale: 'New Sale',
    printInvoice: 'Print Invoice',
    pkr: 'PKR',
    electronics: 'Electronics',
    clothing: 'Clothing', 
    food: 'Food',
    books: 'Books',
    sports: 'Sports',
    
    // Loans & Credit Management
    searchByCustomer: 'Search by customer name, phone, or sale ID...',
    allOutstanding: 'All Outstanding',
    pendingNoPayment: 'Pending (No Payment)',
    partialPaymentFilter: 'Partial Payment',
    totalOutstandingSales: 'Total Outstanding Sales',
    totalOutstandingAmount: 'Total Outstanding Amount',
    totalCollected: 'Total Collected',
    loadingText: 'Loading...',
    fetchingOutstandingPayments: 'Fetching outstanding payments',
    noOutstandingPayments: 'No outstanding payments found',
    allSalesFullyPaid: 'All sales have been fully paid',
    walkInCustomer: 'Walk-in Customer',
    noPayment: 'No Payment',
    partialPaid: 'Partial Paid',
    paid: 'Paid',
    view: 'View',
    addPayment: 'Add Payment',
    recordPayment: 'Record Payment',
    paymentAmount: 'Payment Amount',
    enterAmountBeingPaid: 'Enter amount being paid',
    remainingAfterPayment: 'Remaining after payment',
    notesOptional: 'Notes (Optional)',
    addNotesAboutPayment: 'Add any notes about this payment...',
    processing: 'Processing...',
    paymentRecordedSuccess: 'Payment recorded successfully!',
    failedToRecordPayment: 'Failed to record payment',
    errorRecordingPayment: 'Error recording payment',
    
    // Ograi - Agricultural/Supplier Management
    ograi: 'Ograi',
    ograiSupplierTracking: 'Ograi - Supplier Payment Tracking',
    manageSupplierPurchases: 'Manage supplier purchases, payments, and transport charges',
    totalPurchases: 'Total Purchases',
    totalDue: 'Total Due',
    addNewTransaction: 'Add New Transaction',
    searchBySupplier: 'Search by supplier name or product...',
    supplierName: 'Supplier Name',
    contactNumber: 'Contact Number',
    transactionDate: 'Transaction Date',
    pricePerUnit: 'Price per Unit',
    amountPaid: 'Amount Paid',
    remainingAmount: 'Remaining Amount',
    transportFee: 'Transport/Rent Fee',
    transportPaid: 'Transport Paid',
    transportRemaining: 'Transport Remaining',
    bankTransfer: 'Bank Transfer',
    cheque: 'Cheque',
    notes: 'Notes',
    anyAdditionalNotes: 'Any additional notes or agreements...',
    transactionSummary: 'Transaction Summary',
    totalPurchaseAmount: 'Total Purchase Amount',
    overpaidAmount: 'Overpaid Amount',
    saving: 'Saving...',
    saveTransaction: 'Save Transaction',
    paymentHistory: 'Payment History',
    transactionDetails: 'Transaction Details',
    supplier: 'Supplier',
    product: 'Product',
    totalPaid: 'Total Paid',
    paymentNumber: 'Payment #',
    productPayment: 'Product Payment',
    transportPayment: 'Transport Payment',
    totalPayment: 'Total Payment',
    method: 'Method',
    installment: 'Installment',
    noPaymentHistory: 'No payment history',
    noPaymentsMade: 'No payments have been made for this transaction yet',
    close: 'Close',
    recordNewPayment: 'Record New Payment',
    paymentDate: 'Payment Date',
    paymentNotes: 'Payment notes...',
    recordPayment: 'Record Payment',
    transactionHistory: 'Transaction History',
    noTransactionsYet: 'No transactions yet',
    addFirstSupplierTransaction: 'Add your first supplier transaction to get started',
    transport: 'Transport',
    transportDue: 'Transport Due',
    suppliersOverview: 'Suppliers Overview',
    complete: 'Complete',
    overpaid: 'Overpaid',
    pending: 'Pending',
    pay: 'Pay',
    history: 'History',
    
    // Returns
    returnsExchange: 'Returns & Exchange',
    returnsRefunds: 'Returns & Refunds',
    processReturns: 'Process returns quickly and efficiently',
    processProductReturns: 'Process product returns and manage refunds',
    processReturnsManageRefunds: 'Process product returns and manage refunds',
    searchSale: 'Search Sale',
    findSale: 'Find Sale',
    searchByIdPhone: 'Enter Sale ID or Customer Phone',
    searchForSaleToReturn: 'Search for a sale to process return',
    searchSaleToProcessReturn: 'Search for a sale to process return',
    walkInCustomer: 'Walk-in Customer',
    saleNotFoundCheckIdOrPhone: 'Sale not found! Please check the sale ID or phone number.',
    errorSearchingSale: 'Error searching for sale. Please try again.',
    pleaseEnterSaleIdOrPhone: 'Please enter a sale ID or phone number',
    enterSaleIdOrPhone: 'Enter Sale ID or Customer Phone',
    selectItemsToReturn: 'Select Items to Return',
    reasonForReturn: 'Reason for Return',
    pleaseProvideReasonForReturn: 'Please provide a reason for the return...',
    itemsToReturn: 'Items to Return',
    refundAmount: 'Refund Amount',
    processReturn: 'Process Return',
    pleaseSelectItemsToReturn: 'Please select items to return',
    pleaseProvideReason: 'Please provide a reason for return',
    pleaseProvideReturnReason: 'Please provide a reason for return',
    areYouSureProcessReturn: 'Are you sure you want to process this return? Refund amount',
    confirmProcessReturn: 'Are you sure you want to process this return?',
    returnProcessedSuccessfully: 'Return processed successfully!',
    failedToProcessReturn: 'Failed to process return. Please try again.',
    errorProcessingReturn: 'Error processing return. Please try again.',
    failedToLoadRecentReturns: 'Failed to load recent returns',
    failedToLoadReturns: 'Failed to load recent returns',
    recentReturns: 'Recent Returns',
    noRecentReturns: 'No recent returns',
    returnNumber: 'Return #',
    return: 'Return',
    saleNumber: 'Sale #',
    sale: 'Sale',
    refund: 'Refund',
    reason: 'Reason',
    returnProcessedSuccessfullyTitle: 'Return Processed Successfully!',
    returnProcessedMessage: 'The return has been processed and inventory has been updated.',
    returnProcessedInventoryUpdated: 'The return has been processed and inventory has been updated.',
    search: 'Search',
    search: 'Search',
    saleDetails: 'Sale Details',
    customer: 'Customer',
    selectItemsReturn: 'Select Items to Return',
    returnQuantity: 'Return Quantity',
    returnReason: 'Return Reason',
    processReturn: 'Process Return',
    recentReturns: 'Recent Returns',
    reason: 'Reason',
    status: 'Status',
    staff: 'Staff',
    amount: 'Amount',
    processing: 'Processing',
    completed: 'Completed',
    
    // Reports
    reportsAnalytics: 'Reports & Analytics',
    loadingReportData: 'Loading report data...',
    exportPdf: 'Export PDF',
    exportExcel: 'Export Excel',
    salesReport: 'Sales Report',
    inventoryReport: 'Inventory Report',
    financialReport: 'Financial Report',
    totalSales: 'Total Sales',
    totalRevenue: 'Total Revenue',
    topProduct: 'Top Product',
    unitsSold: 'Units Sold',
    averageOrderValue: 'Average Order Value',
    dailySalesTrend: 'Daily Sales Trend',
    topSellingProducts: 'Top Selling Products',
    salesByCategory: 'Sales by Category',
    revenue: 'Revenue',
    lowStockAlert: 'Low Stock Alert',
    totalProducts: 'Total Products',
    lowStockItems: 'Low Stock Items',
    requiresAttention: 'Requires attention',
    outOfStock: 'Out of Stock',
    low: 'Low',
    currentStock: 'Current Stock',
    minimumStock: 'Minimum Stock',
    stockValueByCategory: 'Stock Value by Category',
    stockValue: 'Stock Value',
    current: 'Current',
    minimum: 'Minimum',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Profit',
    profitMargin: 'Profit Margin',
    expenseBreakdown: 'Expense Breakdown',
    fromLastMonth: 'from last month',
    monthlyFinancialTrend: 'Monthly Financial Trend',
    month: 'Month',
    expenses: 'Expenses',
    profit: 'Profit',
    margin: 'Margin',
    exportingReportAs: 'Exporting report as',
    uncategorized: 'Uncategorized',
    
    // Common
    inventoryPro: 'Inventory Pro',
    adminUser: 'Admin User',
    storeManager: 'Store Manager',
    logout: 'Logout',
    loading: 'Loading...',
    noDataFound: 'No data found',
    confirmDelete: 'Are you sure you want to delete this?',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    required: 'Required',
    optional: 'Optional',
    actions: 'Actions',
    details: 'Details',
    dueDate: 'Due Date',
    from: 'from',
    to: 'to',
    all: 'All',
    new: 'New',
    units: 'units',
    perTransaction: 'Per transaction',
    activeCategories: 'Active categories',
    inInventory: 'In inventory',
    critical: 'Critical',
    totalInventoryValue: 'Total inventory value',
    product: 'Product',
    items: 'Items',
    categories: 'Categories',
    newThisWeek: 'new this week',
    findSale: 'Find Sale',
    searchViewTransactions: 'Search and view past transactions',
    recentReturnsTitle: 'Recent Returns',
    viewLatestReturns: 'View latest product returns',
    returnsRefunds: 'Returns & Refunds',
    processReturnsRefunds: 'Process product returns and manage refunds'
  },
  
  ur: {
    // Navigation
    dashboard: 'ڈیش بورڈ',
    products: 'مصنوعات',
    sales: 'فروخت',
    salesHistory: 'فروخت کی تاریخ',
    searchBySaleIdCustomer: 'سیل آئی ڈی یا کسٹمر کے ذریعے تلاش کریں',
    allSales: 'تمام فروخت',
    inSelectedPeriod: 'منتخب مدت میں',
    beforeDiscounts: 'ڈسکاؤنٹ سے پہلے',
    afterExpenses: 'اخراجات کے بعد',
    recentSales: 'حالیہ فروخت',
    loadingSales: 'فروخت لوڈ ہو رہی ہے...',
    noSalesFound: 'کوئی فروخت نہیں ملی',
    errorFetchingSales: 'فروخت لانے میں خرابی',
    remaining: 'باقی',
    returns: 'واپسی',
    reports: 'رپورٹس',
    inventoryManagement: 'انوینٹری منیجمنٹ',
    loansCredit: 'قرض/کریڈٹ',
    loanHistory: 'قرض کی تاریخ',
    loanCreditManagement: 'قرض اور کریڈٹ منیجمنٹ',
    loanHistorySubtitle: 'فروخت اور ادائیگی کی تاریخ دیکھیں اور منتظم کریں',
    fullyPaid: 'مکمل ادا شدہ',
    partiallyPaid: 'جزوی ادا شدہ',
    totalPaid: 'کل ادا شدہ',
    totalPending: 'کل بقایا',
    salesAndPaymentHistory: 'فروخت اور ادائیگی کی تاریخ',
    itemsSold: 'فروخت شدہ آئٹمز',
    noPaymentHistory: 'ادائیگی کی کوئی تاریخ نہیں',
    totalSalesAmount: 'کل فروخت کی رقم',
    amountCollected: 'وصول شدہ رقم',
    yetToCollect: 'ابھی وصول کرنا باقی',
    fromAllSales: 'تمام فروخت سے',
    loadingData: 'ڈیٹا لوڈ ہو رہا ہے...',
    totalProfit: 'کل منافع',
    
    // Dashboard
    welcomeBack: 'خوش آمدید! آپ کے کاروبار کا جائزہ',
    todaysSales: 'آج کی فروخت',
    totalRevenue: 'کل آمدنی',
    totalProducts: 'کل مصنوعات',
    lowStockItems: 'کم اسٹاک آئٹمز',
    pendingReturns: 'زیر التواء واپسیاں',
    recentActivities: 'حالیہ سرگرمیاں',
    viewAll: 'سب دیکھیں',
    fromYesterday: 'کل سے',
    thisMonth: 'اس ماہ',
    requiresAttention: 'توجہ درکار',
    processSoon: 'جلد پروسیس کریں',
    
    // Product Management
    productManagement: 'پروڈکٹ منیجمنٹ',
    addProduct: 'پروڈکٹ شامل کریں',
    addCategory: 'کیٹیگری شامل کریں',
    categories: 'کیٹیگریز',
    searchProducts: 'پروڈکٹ تلاش کریں...',
    allCategories: 'تمام کیٹیگریز',
    price: 'قیمت',
    stock: 'اسٹاک',
    minStock: 'کم سے کم اسٹاک',
    category: 'کیٹیگری',
    description: 'تفصیل',
    barcode: 'بار کوڈ',
    edit: 'ترمیم',
    delete: 'حذف کریں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    addNewProduct: 'نیا پروڈکٹ شامل کریں',
    editProduct: 'پروڈکٹ میں ترمیم',
    productName: 'پروڈکٹ کا نام',
    quantity: 'مقدار',
    minimumStock: 'کم سے کم اسٹاک',
    inStock: 'دستیاب',
    lowStock: 'کم اسٹاک',
    outOfStock: 'اسٹاک ختم',
    deleteProduct: 'پروڈکٹ حذف کریں',
    deleteProductConfirm: 'کیا آپ واقعی اس پروڈکٹ کو حذف کرنا چاہتے ہیں؟',
    deleteCategory: 'کیٹیگری حذف کریں',
    deleteCategoryConfirm: 'کیا آپ واقعی اس کیٹیگری کو حذف کرنا چاہتے ہیں؟ اس کیٹیگری میں موجود پروڈکٹس حذف نہیں ہوں گے۔',
    editCategory: 'کیٹیگری میں ترمیم',
    addNewCategory: 'نئی کیٹیگری شامل کریں',
    categoryName: 'کیٹیگری کا نام',
    categoryDescription: 'تفصیل',
    selectCategory: 'کیٹیگری منتخب کریں',
    loadingProducts: 'پروڈکٹس لوڈ ہو رہے ہیں...',
    noProductsFound: 'کوئی پروڈکٹ نہیں ملا',
    noCategoriesFound: 'کوئی کیٹیگری نہیں ملی',
    boxes: 'باکس',
    units: 'یونٹس',
    products: 'پروڈکٹس',
    unitsPerBox: 'فی باکس یونٹس',
    profitPerUnit: 'فی یونٹ منافع (PKR)',
    profitPerBox: 'فی باکس منافع (PKR)',
    profitEarnedPerUnit: 'فی یونٹ حاصل شدہ منافع',
    profitEarnedPerBox: 'فی باکس حاصل شدہ منافع',
    addStockBy: 'اسٹاک شامل کریں:',
    individualQuantity: 'انفرادی مقدار',
    boxesUnits: 'باکس + یونٹس',
    totalQuantityUnits: 'کل مقدار (یونٹس میں)',
    enterTotalUnits: 'یونٹس کی کل تعداد درج کریں',
    thisEquals: 'یہ برابر ہے:',
    and: 'اور',
    looseUnits: 'اضافی یونٹس',
    numberOfBoxes: 'باکسوں کی تعداد',
    howManyBoxes: 'کتنے باکس؟',
    extraUnits: 'اضافی یونٹس',
    minimumStockAlert: 'کم سے کم اسٹاک الرٹ (یونٹس میں)',
    alertWhenStockFalls: 'جب اسٹاک کم ہو تو الرٹ',
    updateProduct: 'پروڈکٹ اپ ڈیٹ کریں',
    failedToUpdateProduct: 'پروڈکٹ اپ ڈیٹ کرنے میں ناکام',
    failedToCreateProduct: 'پروڈکٹ بنانے میں ناکام',
    failedToDeleteProduct: 'پروڈکٹ حذف کرنے میں ناکام',
    productDeletedSuccessfully: 'پروڈکٹ کامیابی سے حذف ہوئی',
    cannotDeleteProductWithHistory: 'اس پروڈکٹ کو حذف نہیں کیا جا سکتا۔ اس کی فروخت یا واپسی کی تاریخ ہے۔ اس کی بجائے مقدار 0 کریں۔',
    failedToUpdateCategory: 'کیٹیگری اپ ڈیٹ کرنے میں ناکام',
    failedToCreateCategory: 'کیٹیگری بنانے میں ناکام',
    failedToDeleteCategory: 'کیٹیگری حذف کرنے میں ناکام',
    saving: 'محفوظ ہو رہا ہے...',
    updateCategory: 'کیٹیگری اپ ڈیٹ کریں',
    enterCategoryName: 'کیٹیگری کا نام درج کریں',
    enterCategoryDescription: 'کیٹیگری کی تفصیل درج کریں (اختیاری)',
    howManyUnitsInBox: 'ایک باکس میں کتنے یونٹس؟',
    alertWhenStockFallsBelow: 'جب اسٹاک اس سے کم ہو تو الرٹ',
    descriptionOptional: 'تفصیل (اختیاری)',
    
    // Sales POS
    searchProducts: 'پروڈکٹ تلاش کریں',
    searchProductsBarcode: 'نام سے تلاش کریں یا بارکوڈ اسکین کریں...',
    shoppingCart: 'شاپنگ کارٹ',
    items: 'آئٹمز',
    emptyCart: 'آپ کا کارٹ خالی ہے',
    addItemsToStart: 'شروع کرنے کے لیے آئٹمز شامل کریں',
    subtotal: 'ذیلی کل',
    tax: 'ٹیکس',
    total: 'کل',
    checkout: 'چیک آؤٹ',
    customerInfo: 'گاہک کی معلومات',
    customerName: 'گاہک کا نام',
    phone: 'فون',
    email: 'ای میل',
    paymentMethod: 'ادائیگی کا طریقہ',
    cash: 'نقد',
    card: 'کارڈ',
    upi: 'یو پی آئی',
    processSale: 'فروخت پروسیس کریں',
    receipt: 'رسید',
    paymentSuccessful: 'ادائیگی کامیاب!',
    saleId: 'فروخت آئی ڈی',
    date: 'تاریخ',
    printReceipt: 'رسید پرنٹ کریں',
    remove: 'ہٹائیں',
    grandTotal: 'مجموعی رقم',
    proceedToCheckout: 'چیک آؤٹ کی طرف بڑھیں',
    enterCustomerName: 'گاہک کا نام درج کریں',
    phoneNumber: 'فون نمبر',
    enterPhoneNumber: 'فون نمبر درج کریں',
    emailOptional: 'ای میل (اختیاری)',
    enterEmailAddress: 'ای میل ایڈریس درج کریں',
    paymentType: 'ادائیگی کی قسم',
    fullPayment: 'مکمل ادائیگی',
    partialPayment: 'جزوی ادائیگی (قرض/کریڈٹ)',
    amountPaidNow: 'ابھی ادا کی گئی رقم',
    enterAmountPayingNow: 'گاہک اب جو رقم ادا کر رہا ہے وہ درج کریں',
    remaining: 'باقی',
    dueDate: 'آخری تاریخ (اختیاری)',
    totalAmount: 'کل رقم',
    amountPayingNow: 'ابھی ادا کی جانے والی رقم',
    remainingAmount: 'باقی رقم',
    notEnoughStock: 'کافی اسٹاک دستیاب نہیں ہے!',
    outOfStockProduct: 'یہ پروڈکٹ اسٹاک میں نہیں ہے!',
    cartEmpty: 'کارٹ خالی ہے! براہ کرم کارٹ میں آئٹمز شامل کریں۔',
    saleProcessedSuccess: 'فروخت کامیابی سے پروسیس ہوئی!',
    failedToProcessSale: 'فروخت پروسیس کرنے میں ناکام۔ دوبارہ کوشش کریں۔',
    errorProcessingSale: 'فروخت پروسیس کرنے میں خرابی۔ دوبارہ کوشش کریں۔',
    newSale: 'نئی فروخت',
    printInvoice: 'انوائس پرنٹ کریں',
    pkr: 'روپے',
    electronics: 'الیکٹرانکس',
    clothing: 'کپڑے',
    food: 'کھانا',
    books: 'کتابیں',
    sports: 'کھیل',
    
    // Loans & Credit Management
    searchByCustomer: 'گاہک کے نام، فون، یا سیل آئی ڈی سے تلاش کریں...',
    allOutstanding: 'تمام بقایا',
    pendingNoPayment: 'زیر التواء (کوئی ادائیگی نہیں)',
    partialPaymentFilter: 'جزوی ادائیگی',
    totalOutstandingSales: 'کل بقایا فروخت',
    totalOutstandingAmount: 'کل بقایا رقم',
    totalCollected: 'کل وصول شدہ',
    loadingText: 'لوڈ ہو رہا ہے...',
    fetchingOutstandingPayments: 'بقایا ادائیگیاں لا رہے ہیں',
    noOutstandingPayments: 'کوئی بقایا ادائیگی نہیں ملی',
    allSalesFullyPaid: 'تمام فروخت مکمل طور پر ادا کی گئی ہیں',
    walkInCustomer: 'واک ان کسٹمر',
    noPayment: 'کوئی ادائیگی نہیں',
    partialPaid: 'جزوی ادا شدہ',
    paid: 'ادا شدہ',
    view: 'دیکھیں',
    addPayment: 'ادائیگی شامل کریں',
    recordPayment: 'ادائیگی ریکارڈ کریں',
    paymentAmount: 'ادائیگی کی رقم',
    enterAmountBeingPaid: 'ادا کی جانے والی رقم درج کریں',
    remainingAfterPayment: 'ادائیگی کے بعد باقی',
    notesOptional: 'نوٹس (اختیاری)',
    addNotesAboutPayment: 'اس ادائیگی کے بارے میں کوئی نوٹ شامل کریں...',
    processing: 'پروسیسنگ...',
    paymentRecordedSuccess: 'ادائیگی کامیابی سے ریکارڈ ہوئی!',
    failedToRecordPayment: 'ادائیگی ریکارڈ کرنے میں ناکام',
    errorRecordingPayment: 'ادائیگی ریکارڈ کرنے میں خرابی',
    
    // Ograi - Agricultural/Supplier Management
    ograi: 'اوگرائی',
    ograiSupplierTracking: 'اوگرائی - سپلائر ادائیگی ٹریکنگ',
    manageSupplierPurchases: 'سپلائر کی خرید، ادائیگی، اور ٹرانسپورٹ چارجز کا انتظام کریں',
    totalPurchases: 'کل خریداری',
    totalDue: 'کل بقایا',
    addNewTransaction: 'نیا لین دین شامل کریں',
    searchBySupplier: 'سپلائر کے نام یا پروڈکٹ سے تلاش کریں...',
    supplierName: 'سپلائر کا نام',
    contactNumber: 'رابطہ نمبر',
    transactionDate: 'لین دین کی تاریخ',
    pricePerUnit: 'فی یونٹ قیمت',
    amountPaid: 'ادا شدہ رقم',
    remainingAmount: 'باقی رقم',
    transportFee: 'ٹرانسپورٹ/کرایہ فیس',
    transportPaid: 'ٹرانسپورٹ ادا شدہ',
    transportRemaining: 'ٹرانسپورٹ باقی',
    bankTransfer: 'بینک ٹرانسفر',
    cheque: 'چیک',
    notes: 'نوٹس',
    anyAdditionalNotes: 'کوئی اضافی نوٹس یا معاہدے...',
    transactionSummary: 'لین دین کا خلاصہ',
    totalPurchaseAmount: 'کل خرید کی رقم',
    overpaidAmount: 'زیادہ ادا شدہ رقم',
    saving: 'محفوظ کر رہے ہیں...',
    saveTransaction: 'لین دین محفوظ کریں',
    paymentHistory: 'ادائیگی کی تاریخ',
    transactionDetails: 'لین دین کی تفصیلات',
    supplier: 'سپلائر',
    product: 'پروڈکٹ',
    totalPaid: 'کل ادا شدہ',
    paymentNumber: 'ادائیگی #',
    productPayment: 'پروڈکٹ ادائیگی',
    transportPayment: 'ٹرانسپورٹ ادائیگی',
    totalPayment: 'کل ادائیگی',
    method: 'طریقہ',
    installment: 'قسط',
    noPaymentHistory: 'ادائیگی کی کوئی تاریخ نہیں',
    noPaymentsMade: 'اس لین دین کے لیے ابھی تک کوئی ادائیگی نہیں کی گئی',
    close: 'بند کریں',
    recordNewPayment: 'نئی ادائیگی ریکارڈ کریں',
    paymentDate: 'ادائیگی کی تاریخ',
    paymentNotes: 'ادائیگی کے نوٹس...',
    recordPayment: 'ادائیگی ریکارڈ کریں',
    transactionHistory: 'لین دین کی تاریخ',
    noTransactionsYet: 'ابھی تک کوئی لین دین نہیں',
    addFirstSupplierTransaction: 'شروع کرنے کے لیے اپنا پہلا سپلائر لین دین شامل کریں',
    transport: 'ٹرانسپورٹ',
    transportDue: 'ٹرانسپورٹ بقایا',
    suppliersOverview: 'سپلائرز کا جائزہ',
    complete: 'مکمل',
    overpaid: 'زیادہ ادا شدہ',
    pending: 'زیر التواء',
    pay: 'ادا کریں',
    history: 'تاریخ',
    
    // Returns
    returnsExchange: 'واپسی اور تبدیلی',
    returnsRefunds: 'واپسی اور رقم کی واپسی',
    processReturns: 'واپسیوں کو جلدی اور مؤثر طریقے سے پروسیس کریں',
    processProductReturns: 'پروڈکٹ کی واپسی اور رقم کی واپسی کا انتظام کریں',
    processReturnsManageRefunds: 'پروڈکٹ کی واپسی اور رقم کی واپسی کا انتظام کریں',
    searchSale: 'فروخت تلاش کریں',
    findSale: 'فروخت تلاش کریں',
    searchByIdPhone: 'سیل آئی ڈی یا فون نمبر درج کریں',
    searchForSaleToReturn: 'واپسی کے لیے فروخت تلاش کریں',
    searchSaleToProcessReturn: 'واپسی کے لیے فروخت تلاش کریں',
    walkInCustomer: 'واک ان کسٹمر',
    saleNotFoundCheckIdOrPhone: 'فروخت نہیں ملی! براہ کرم سیل آئی ڈی یا فون نمبر چیک کریں۔',
    errorSearchingSale: 'فروخت تلاش کرنے میں خرابی۔ دوبارہ کوشش کریں۔',
    pleaseEnterSaleIdOrPhone: 'براہ کرم سیل آئی ڈی یا فون نمبر درج کریں',
    enterSaleIdOrPhone: 'سیل آئی ڈی یا کسٹمر فون درج کریں',
    selectItemsToReturn: 'واپس کرنے کے لیے آئٹمز منتخب کریں',
    reasonForReturn: 'واپسی کی وجہ',
    pleaseProvideReasonForReturn: 'براہ کرم واپسی کی وجہ فراہم کریں...',
    itemsToReturn: 'واپس کرنے کے آئٹمز',
    refundAmount: 'رقم کی واپسی',
    processReturn: 'واپسی پروسیس کریں',
    pleaseSelectItemsToReturn: 'براہ کرم واپس کرنے کے لیے آئٹمز منتخب کریں',
    pleaseProvideReason: 'براہ کرم واپسی کی وجہ فراہم کریں',
    pleaseProvideReturnReason: 'براہ کرم واپسی کی وجہ فراہم کریں',
    areYouSureProcessReturn: 'کیا آپ واقعی اس واپسی کو پروسیس کرنا چاہتے ہیں؟ رقم کی واپسی',
    confirmProcessReturn: 'کیا آپ واقعی اس واپسی کو پروسیس کرنا چاہتے ہیں؟',
    returnProcessedSuccessfully: 'واپسی کامیابی سے پروسیس ہوئی!',
    failedToProcessReturn: 'واپسی پروسیس کرنے میں ناکام۔ دوبارہ کوشش کریں۔',
    errorProcessingReturn: 'واپسی پروسیس کرنے میں خرابی۔ دوبارہ کوشش کریں۔',
    failedToLoadRecentReturns: 'حالیہ واپسیاں لوڈ کرنے میں ناکام',
    failedToLoadReturns: 'حالیہ واپسیاں لوڈ کرنے میں ناکام',
    recentReturns: 'حالیہ واپسیاں',
    noRecentReturns: 'کوئی حالیہ واپسی نہیں',
    returnNumber: 'واپسی #',
    return: 'واپسی',
    saleNumber: 'فروخت #',
    sale: 'فروخت',
    refund: 'رقم کی واپسی',
    reason: 'وجہ',
    returnProcessedSuccessfullyTitle: 'واپسی کامیابی سے پروسیس ہوئی!',
    returnProcessedMessage: 'واپسی پروسیس ہو گئی ہے اور انوینٹری اپ ڈیٹ ہو گئی ہے۔',
    returnProcessedInventoryUpdated: 'واپسی پروسیس ہو گئی ہے اور انوینٹری اپ ڈیٹ ہو گئی ہے۔',
    search: 'تلاش کریں',
    search: 'تلاش',
    saleDetails: 'فروخت کی تفصیلات',
    customer: 'گاہک',
    selectItemsReturn: 'واپسی کے لیے آئٹمز منتخب کریں',
    returnQuantity: 'واپسی کی مقدار',
    returnReason: 'واپسی کی وجہ',
    processReturn: 'واپسی پروسیس کریں',
    recentReturns: 'حالیہ واپسیاں',
    reason: 'وجہ',
    status: 'حالت',
    staff: 'عملہ',
    amount: 'رقم',
    processing: 'پروسیسنگ',
    completed: 'مکمل',
    
    // Reports
    reportsAnalytics: 'رپورٹس اور تجزیات',
    loadingReportData: 'رپورٹ ڈیٹا لوڈ ہو رہا ہے...',
    exportPdf: 'پی ڈی ایف ایکسپورٹ',
    exportExcel: 'ایکسل ایکسپورٹ',
    salesReport: 'سیلز رپورٹ',
    inventoryReport: 'انوینٹری رپورٹ',
    financialReport: 'مالیاتی رپورٹ',
    totalSales: 'کل فروخت',
    totalRevenue: 'کل آمدنی',
    topProduct: 'سب سے اوپر پروڈکٹ',
    unitsSold: 'فروخت شدہ یونٹس',
    averageOrderValue: 'اوسط آرڈر ویلیو',
    dailySalesTrend: 'روزانہ فروخت کا رجحان',
    topSellingProducts: 'سب سے زیادہ فروخت ہونے والی مصنوعات',
    salesByCategory: 'کیٹیگری کے حساب سے فروخت',
    revenue: 'آمدنی',
    lowStockAlert: 'کم اسٹاک الرٹ',
    totalProducts: 'کل پروڈکٹس',
    lowStockItems: 'کم اسٹاک آئٹمز',
    requiresAttention: 'توجہ کی ضرورت',
    outOfStock: 'اسٹاک ختم',
    low: 'کم',
    currentStock: 'موجودہ اسٹاک',
    minimumStock: 'کم سے کم اسٹاک',
    stockValueByCategory: 'کیٹیگری کے حساب سے اسٹاک کی قیمت',
    stockValue: 'اسٹاک کی قیمت',
    current: 'موجودہ',
    minimum: 'کم سے کم',
    totalExpenses: 'کل اخراجات',
    netProfit: 'خالص منافع',
    profitMargin: 'منافع مارجن',
    expenseBreakdown: 'اخراجات کی تفصیل',
    fromLastMonth: 'پچھلے مہینے سے',
    monthlyFinancialTrend: 'ماہانہ مالیاتی رجحان',
    month: 'مہینہ',
    expenses: 'اخراجات',
    profit: 'منافع',
    margin: 'مارجن',
    exportingReportAs: 'رپورٹ ایکسپورٹ کی جا رہی ہے',
    uncategorized: 'غیر زمرہ بند',
    
    // Common
    inventoryPro: 'انوینٹری پرو',
    adminUser: 'ایڈمن یوزر',
    storeManager: 'اسٹور منیجر',
    logout: 'لاگ آؤٹ',
    loading: 'لوڈ ہو رہا ہے...',
    noDataFound: 'کوئی ڈیٹا نہیں ملا',
    confirmDelete: 'کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟',
    success: 'کامیابی',
    error: 'خرابی',
    warning: 'انتباہ',
    info: 'معلومات',
    required: 'ضروری',
    optional: 'اختیاری',
    actions: 'اعمال',
    details: 'تفصیلات',
    dueDate: 'آخری تاریخ',
    from: 'سے',
    to: 'تک',
    all: 'تمام',
    new: 'نیا',
    units: 'یونٹس',
    perTransaction: 'فی ٹرانزیکشن',
    activeCategories: 'فعال کیٹیگریز',
    inInventory: 'انوینٹری میں',
    critical: 'شدید',
    totalInventoryValue: 'کل انوینٹری کی قیمت',
    product: 'پروڈکٹ',
    items: 'آئٹمز',
    categories: 'کیٹیگریز',
    newThisWeek: 'اس ہفتے نیا',
    findSale: 'فروخت تلاش کریں',
    searchViewTransactions: 'ماضی کی لین دین تلاش اور دیکھیں',
    recentReturnsTitle: 'حالیہ واپسیاں',
    viewLatestReturns: 'تازہ ترین واپسیاں دیکھیں',
    returnsRefunds: 'واپسیاں اور رقم کی واپسی',
    processReturnsRefunds: 'پروڈکٹ کی واپسی اور رقم کی واپسی کا انتظام کریں'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  
  useEffect(() => {
    const savedLang = localStorage.getItem('language') || 'en';
    setLanguage(savedLang);
    document.dir = savedLang === 'ur' ? 'rtl' : 'ltr';
  }, []);
  
  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'ur' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
    document.dir = newLang === 'ur' ? 'rtl' : 'ltr';
  };
  
  const t = (key) => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}