import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { NotificationProvider } from "@/components/NotificationSystem";
import { Toaster } from "sonner";
import { NextIntlClientProvider } from "next-intl";
import { Providers } from "@/components/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        suppressHydrationWarning={true}
        style={{ fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' }}
      >
        <Providers>
          <NotificationProvider>
            <LanguageProvider>{children}</LanguageProvider>
          </NotificationProvider>
        </Providers>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
